name: senv
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.12
    - numpy<=2.1.2
    - pandas<=2.10
    - matplotlib<=3.8
    - freud
    - seaborn<=0.12.2
    - scikit-learn<=1.3
    - PyDrive2<=1.20.0
    - setuptools-rust<=1.10.1
    - gspread<=5.8.0
    - google-auth<=2.20.0
    - google-auth-oauthlib<=1.0.0
    - google-auth-httplib2<=0.1.0
    - jupyter
    - pip